In [38]:
# 2021-03-12 (edited)

# Import master csv file
input_dir = './wandb_table'

# csv_name = 'wandb_export_2022-05-04T00_45_53.316+09_00.csv'
csv_name = 'pooled2single.csv'
output_dir = './wandb_table/pivot_table'

import pandas as pd
import numpy as np
import os


# Basic data cleaning
data = pd.read_csv(os.path.join(input_dir,csv_name))
rundata = data.copy().round(3)

In [39]:
rundata.columns

Index(['Name', 'State', 'Notes', 'User', 'Tags', 'Created', 'Runtime', 'Sweep',
       'DDP', 'batch_size',
       ...
       'valid/eicu_loss', 'valid/mimic3_auprc', 'valid/mimic3_auroc',
       'valid/mimic3_loss', 'valid/mimic3_mimic4_eicu_auprc',
       'valid/mimic3_mimic4_eicu_auroc', 'valid/mimic3_mimic4_eicu_loss',
       'valid/mimic4_auprc', 'valid/mimic4_auroc', 'valid/mimic4_loss'],
      dtype='object', length=116)

In [33]:
test_columns = [col for col in rundata.columns if 'test' in col and 'auprc' in col]

In [36]:
temp['test_mimic3_auprc'].fillna(temp['test/mimic3_auprc'], inplace=True)
temp['test_eicu_auprc'].fillna(temp['test/eicu_auprc'],inplace=True)
temp['test_mimic4_auprc'].fillna(temp['test/mimic4_auprc'], inplace=True)

KeyError: 'test/eicu_auprc'

In [9]:
rundata['pretrained_load']

0     w2v
1     w2v
2     w2v
3     w2v
4     w2v
5     w2v
6     w2v
7     w2v
8     w2v
9     w2v
10    w2v
11    w2v
12    w2v
13    w2v
Name: pretrained_load, dtype: object

In [28]:
temp = rundata.loc[:, ['input2emb_model','pred_target', 'table', 'seed', 'src_data', 'pretrained_load']+test_columns]
#temp = rundata.loc[:, ['input2emb_model','pred_target', 'table', 'seed', 'src_data', 'test/eicu_auprc','test/mimic3_auprc', 'test_mimic4_auprc']]

In [35]:
temp['test_mimic3_auprc']= pd.Series()
temp['test_eicu_auprc']= pd.Series()
temp['test_mimic4_auprc']= pd.Series()

/tmp/ipykernel_33408/720435437.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  temp['test_mimic3_auprc']= pd.Series()
/tmp/ipykernel_33408/720435437.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  temp['test_eicu_auprc']= pd.Series()
/tmp/ipykernel_33408/720435437.py:3: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  temp['test_mimic4_auprc']= pd.Series()

In [14]:
temp['test_mimic3_auprc'].fillna(temp['test/mimic3_auprc'], inplace=True)
#temp['test_eicu_auprc'].fillna(temp['test/eicu_auprc'],inplace=True)
# temp['test_mimic4_auprc'].fillna(temp['test/eicu_auprc'],inplace=True)

In [190]:
test_columns

['test/eicu_auprc', 'test/mimic3_auprc', 'test/mimic4_auprc']

In [191]:
temp

,input2emb_model,pred_target,table,seed,src_data,pretrained_load,test/eicu_auprc,test/mimic3_auprc,test/mimic4_auprc,test_eicu_auprc
0,descemb_bert,fi_ac,whole,2023,eicu,w2v,0.537,NaN,NaN,0.537
1,descemb_bert,los3,whole,2022,eicu,w2v,0.573,NaN,NaN,0.573
2,descemb_bert,fi_ac,whole,2022,eicu,w2v,0.537,NaN,NaN,0.537
3,descemb_bert,fi_ac,whole,2021,eicu,w2v,0.541,NaN,NaN,0.541
4,descemb_bert,los3,whole,2021,eicu,w2v,0.576,NaN,NaN,0.576
5,descemb_bert,los3,whole,2020,eicu,w2v,0.579,NaN,NaN,0.579
6,descemb_bert,fi_ac,whole,2020,eicu,w2v,0.529,NaN,NaN,0.529

In [182]:
temp.head()

,input2emb_model,pred_target,table,seed,src_data,pretrained_load,test/eicu_auprc,test/mimic3_auprc,test/mimic4_auprc,test_mimic3_auprc
0,descemb_bert,fi_ac,whole,2023,eicu,w2v,0.537,NaN,NaN,NaN
1,descemb_bert,los3,whole,2022,eicu,w2v,0.573,NaN,NaN,NaN
2,descemb_bert,fi_ac,whole,2022,eicu,w2v,0.537,NaN,NaN,NaN
3,descemb_bert,fi_ac,whole,2021,eicu,w2v,0.541,NaN,NaN,NaN
4,descemb_bert,los3,whole,2021,eicu,w2v,0.576,NaN,NaN,NaN

In [18]:
#temp = temp[temp['src_data']!='mimic4']
#temp['auprc'] = temp.apply(lambda x: x['test/'+x['src_data']+'_auprc'], axis=1)
temp['auprc'] = temp.apply(lambda x: x['test_'+x['src_data']+'_auprc'], axis=1)
temp = temp[['input2emb_model','pred_target','table', 'seed', 'src_data', 'auprc', 'pretrained_load']]
temp.head()

KeyError: 'test_mimic3_auprc'

In [ ]:
pd.DataFrame(temp.groupby(['input2emb_model','pred_target', 'table','src_data'])['seed'].apply(set).apply(list)).head()

In [115]:
pd.DataFrame(temp.groupby(['input2emb_model','pred_target', 'table','src_data'])['auprc'].apply(set).apply(list)).head()

                                                                                         auprc
input2emb_model pred_target table  src_data
codeemb         dx          select eicu      [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...
                                   mimic3                          [0.755, 0.759, 0.76, 0.753]
                            whole  eicu      [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...
                                   mimic3                         [0.755, 0.752, 0.754, 0.747]
                fi_ac       select eicu                              [nan, nan, nan, nan, nan]

In [32]:
def max_list(x):
    
    seed_list = [np.nan]*5
    for i,j in zip(x.seed, x.auprc):
        seed_list[i-2020] = j
    return seed_list

auprc = pd.DataFrame(temp.groupby(['input2emb_model','pred_target', 'table','src_data'])[['seed', 'auprc']].apply(max_list))
#auprc.to_csv('./data/wandb/auprc.csv')

In [33]:
def max_list(x):
    
    seed_list = [np.nan]*5
    for i in x:
        seed_list[i-2020] = i
    return seed_list
    
    
seed = pd.DataFrame(temp.groupby(['input2emb_model','pred_target', 'table','src_data'])['seed'].apply(set).apply(list).apply(max_list))
#seed.to_csv('./data/wandb/seed.csv')

In [151]:
auprc.reset_index(inplace=True)
split_df = pd.DataFrame(auprc[0].tolist(), columns=['2020','2021','2022','2023','2024'])
df = pd.concat([auprc, split_df], axis=1)
df = df.drop(0, axis=1)
df.head()

NameError: name 'auprc' is not defined

In [75]:
# df.to_csv('./data/wandb/seed2column.csv', index=False)

In [12]:
seed.reset_index(inplace=True)
split_df = pd.DataFrame(seed['seed'].tolist(), columns=['2020','2021','2022','2023','2024'])
df = pd.concat([seed, split_df], axis=1)
df = df.drop('seed', axis=1)
df.head()

,input2emb_model,pred_target,table,src_data,2020,2021,2022,2023,2024
0,descemb,dx,select,eicu,2020,2021.0,2022.0,2023.0,2024.0
1,descemb,dx,select,mimic3,2020,2021.0,2022.0,2023.0,2024.0
2,descemb,dx,select,mimic4,2020,2021.0,2022.0,2023.0,2024.0
3,descemb,dx,whole,eicu,2020,2021.0,2022.0,2023.0,2024.0
4,descemb,dx,whole,mimic4,2020,2021.0,2022.0,2023.0,2024.0

In [27]:
df.to_csv(os.path.join(output_dir, 'DescEmb0507_df.csv'), index=False)

In [20]:
result_mean = pd.pivot_table(temp,
                       columns = [ 'table', 'input2emb_model'],
                          index = ['pred_target','src_data','seed'],
                       values = ['auprc'],
                    )

In [21]:
temp

   input2emb_model pred_target  table  seed src_data  auprc pretrained_load
0     descemb_bert        mort  whole  2021   mimic3    NaN             w2v
1     descemb_bert        mort  whole  2020   mimic3  0.261             w2v
2     descemb_bert        los7  whole  2024   mimic3  0.341             w2v
3     descemb_bert        los7  whole  2023   mimic3  0.318             w2v
4     descemb_bert        los7  whole  2022   mimic3  0.376             w2v
5     descemb_bert        los7  whole  2021   mimic3  0.334             w2v
6     descemb_bert        los7  whole  2020   mimic3  0.387             w2v
7     descemb_bert        los3  whole  2024   mimic3  0.672             w2v
8     descemb_bert        los3  whole  2023   mimic3  0.667             w2v
9     descemb_bert        los3  whole  2022   mimic3  0.654             w2v
10    descemb_bert        los3  whole  2021   mimic3  0.650             w2v
11    descemb_bert        los3  whole  2020   mimic3  0.654             w2v
12    descemb_bert        los3  whole  2020   mimic3    NaN             w2v
13    descemb_bert        los3  whole  2020   mimic3    NaN             w2v

In [44]:
temp.columns

Index(['input2emb_model', 'pred_target', 'table', 'seed', 'src_data', 'auprc'], dtype='object')

In [22]:
result_mean = pd.pivot_table(temp,
                       columns = ['src_data','table', 'input2emb_model', 'pretrained_load'],
                          index = ['pred_target',  'seed'],
                       values = ['auprc'],
                      #aggfunc=['mean']  
                    )

In [23]:
result_mean

                        auprc
src_data               mimic3
table                   whole
input2emb_model  descemb_bert
pretrained_load           w2v
pred_target seed
los3        2020        0.654
            2021        0.650
            2022        0.654
            2023        0.667
            2024        0.672
los7        2020        0.387
            2021        0.334
            2022        0.376
            2023        0.318
            2024        0.341
mort        2020        0.261

In [71]:
result_mean.droplevel([1], axis=0)

                   mean
                  auprc
src_data           eicu  mimic3
table             whole   whole
input2emb_model descemb descemb
pretrained_load     mlm     mlm spanmlm
pred_target
dx                0.540   0.636   0.635
dx                0.538   0.635   0.635
dx                  NaN   0.635   0.634
dx                  NaN   0.635   0.633
dx                  NaN   0.636     NaN
fi_ac             0.492   0.220   0.220
fi_ac             0.489   0.221   0.221
fi_ac             0.491   0.223   0.227
fi_ac               NaN   0.220   0.224
fi_ac               NaN   0.220     NaN
im_disch          0.411   0.430   0.437
im_disch          0.413   0.439   0.440
im_disch            NaN   0.436   0.434
im_disch            NaN   0.438   0.439
im_disch            NaN   0.434   0.438
los3              0.372     NaN   0.402
los3              0.365     NaN   0.403
los3                NaN     NaN   0.401
los3                NaN     NaN   0.416
los3                NaN     NaN   0.404
los7              0.120   0.136   0.132
los7                NaN   0.128   0.132
los7                NaN   0.138   0.139
los7                NaN   0.143   0.138
los7                NaN   0.143   0.135
mort              0.017   0.036   0.033
mort              0.023   0.033   0.034
mort              0.019   0.028   0.039
mort                NaN   0.033   0.035
mort                NaN   0.040   0.042
readm             0.155   0.070   0.065
readm               NaN   0.071   0.074
readm               NaN   0.059   0.062
readm               NaN   0.058   0.062
readm               NaN   0.059   0.065

In [37]:
result_mean.to_csv('/home/ghhur/wandb_table/result_table/CodeEmb_0511.csv')

In [13]:
# def generate_table(result_file:pd.DataFrame, seed_count=False, count_flag=True, std=False, rounding=True):
    
    
#     # Possible combinations for our models
#     conditionlist = [(result_file['bert_induced'] == False),
#                      (result_file['bert_induced'] == True) & (result_file['bert_freeze'] == True) & 
#                              (result_file['cls_freeze'] == True),
#                      (result_file['bert_induced'] == True) & (result_file['bert_freeze'] == True) & 
#                              (result_file['cls_freeze'] == False),
#                      (result_file['bert_induced'] == True) & (result_file['bert_freeze'] == False)]
#     choicelist = ['singleRNN', 'DescEmb_FR', 'DescEmb_FT','BERTfinetune']
#     result_file['model_name'] = np.select(conditionlist, choicelist)
    
    
    
#     result_file = result_file.loc[:, ['model_name','bert_model','bert_induced','seed', 
#                                       'source_file', 'target','item','mimic_test_auprc', 'eicu_test_auprc']]
    
#     result_filter = result_file.copy() #.loc[result_file['target']==target]
     
#     result_mean = pd.pivot_table(result_filter,
#                                columns = ['source_file', 'model_name'],
#                                index = ['item','target','bert_induced', 'bert_model'],
#                                values = ['mimic_test_auprc', 'eicu_test_auprc'],
#                                aggfunc=['mean'])
    
#     result_std = pd.pivot_table(result_filter,
#                                columns = ['source_file', 'model_name'],
#                                index = ['item','target','bert_induced', 'bert_model'],
#                                values = ['mimic_test_auprc', 'eicu_test_auprc'],
#                                aggfunc=['std'])
    
#     result_count = pd.pivot_table(result_filter,
#                                columns = ['source_file', 'model_name'],
#                                index = ['item','target','bert_induced', 'bert_model'],
#                                values = ['mimic_test_auprc', 'eicu_test_auprc'],
#                                aggfunc=['count'])
    
#     if count_flag == True:
#         if rounding==True:
#             RM_drop = result_mean.droplevel([0], axis=1).round(3)
#             RS_drop = result_std.droplevel([0], axis=1).round(3)
#         elif rounding == False:
#             RM_drop = result_mean.droplevel([0], axis=1)
#             RS_drop = result_std.droplevel([0], axis=1)
#         RC_drop = result_count.droplevel([0], axis=1)
        
#         RC_drop = RC_drop[RM_drop.columns]
        
#         for col in range(len(RM_drop.columns)): 
#             RM_drop.iloc[:,col][RC_drop.iloc[:,col] > 10] = 'over'
#             RM_drop.iloc[:,col][RC_drop.iloc[:,col] < 10] = 'under'   
            
#             RS_drop.iloc[:,col][RC_drop.iloc[:,col] > 10] = 'over'
#             RS_drop.iloc[:,col][RC_drop.iloc[:,col] < 10] = 'under'  
    
    
#     if seed_count==False:
#         if count_flag == True:
#             if std==True:
#                 return RS_drop
#             elif std==False:
#                 return RM_drop
#         elif count_flag == False:
#             if std==True:
#                 return result_std
#             elif std==False:
#                 return result_mean
    
#     elif seed_count==True:
#         return RC_drop

In [14]:
# generate_table(rundata, count_flag=True)